### ISSUE TITLE
drop coreapi dependency

### ISSUE THREAD

**Issue by sivang** [ZviBaratz/pylabber#28]
```
(venv) sivan@titan:~/pylabber/pylabber$ ./manage.py generateschema
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/sivan/pylabber/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/sivan/pylabber/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/sivan/pylabber/venv/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/sivan/pylabber/venv/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/sivan/pylabber/venv/lib/python3.6/site-packages/rest_framework/management/commands/generateschema.py", line 20, in handle
    assert coreapi is not None, 'coreapi must be installed.'
AssertionError: coreapi must be installed.

```

**Comment by ZviBaratz** [comment]
The message indicates that in order to generate a schema using django's CLI `coreapi` need to be installed, because it is not installed, and therefore there is no dependency to drop.
